// This file is auto-generated by NextMonkey
declare global {
  const defineHandler: typeof import('next-monkey/runtime')['defineHandler']
  const human: typeof import('../../../../tsPool/monkey/node_modules/.pnpm/human-being@0.0.5/node_modules/human-being')['human']
  const newJob: typeof import('../../../../tsPool/monkey/node_modules/.pnpm/human-being@0.0.5/node_modules/human-being')['newJob']
}
export { defineHandler } from 'next-monkey/runtime';
export { human, newJob } from 'human-being';